import React from 'react'

const Dashboard = () => {
  return (
    <div className="theme-default aui-theme-default">
      <div id="page">
        <div id="main" className="aui-page-panel">
          <div id="main-header">
            <div id="breadcrumb-section">
              <ol id="breadcrumbs">
                <li className="first">
                  <span>
                    <a href="index.html">XeniApp</a>
                  </span>
                </li>
                <li>
                  <span>
                    <a href="XeniApp_542179373.html">XeniApp</a>
                  </span>
                </li>
              </ol>
            </div>
            <h1 id="title-heading" className="pagetitle">
              <span id="title-text">XeniApp : Projects</span>
            </h1>
          </div>

          <div id="content" className="view">
            <div className="page-metadata">
              Created by <span className="author">Gerardo Nizetich</span> on Nov 08, 2023
            </div>
            <div id="main-content" className="wiki-content group">
              <div className="plugin_pagetree">
                <ul className="plugin_pagetree_children_list plugin_pagetree_children_list_noleftspace">
                  <div className="plugin_pagetree_children"></div>
                </ul>

                <fieldset className="hidden">
                  <input type="hidden" name="treeId" value="" />
                  <input
                    type="hidden"
                    name="treeRequestId"
                    value="/wiki/plugins/pagetree/naturalchildren.action?decorator=none&amp;excerpt=false&amp;sort=position&amp;reverse=false&amp;disableLinks=false&amp;expandCurrent=false"
                  />
                  <input type="hidden" name="treePageId" value="583761921" />
                  <input type="hidden" name="noRoot" value="false" />
                  <input type="hidden" name="rootPageId" value="583761921" />
                  <input type="hidden" name="rootPage" value="" />
                  <input type="hidden" name="startDepth" value="1" />
                  <input type="hidden" name="spaceKey" value="XENIAPP" />
                  <input type="hidden" name="i18n-pagetree.loading" value="Loading..." />
                  <input
                    type="hidden"
                    name="i18n-pagetree.error.permission"
                    value="Unable to load page tree. It seems that you do not have permission to view the root page."
                  />
                  <input
                    type="hidden"
                    name="i18n-pagetree.eeror.general"
                    value="There was a problem retrieving the page tree. Please check the server log file for more information."
                  />
                  <input type="hidden" name="loginUrl" value="" />
                  <input type="hidden" name="mobile" value="false" />
                  <fieldset className="hidden">
                    <input type="hidden" name="ancestorId" value="583761921" />
                  </fieldset>
                </fieldset>
              </div>
            </div>
          </div>
        </div>
        <div id="footer" role="contentinfo">
          <section className="footer-body">
            <p>Document generated by Confluence on Jul 09, 2024 08:02</p>
            <div id="footer-logo">
              <a href="http://www.atlassian.com/">Atlassian</a>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}

export default Dashboard
